/**
 * Grid Lock City service worker: installable, fully offline play.
 *
 * - Precache: every runtime file (listed below by tools/build-pwa.mjs) is stored
 *   in one cache named after a hash of their contents. Precached files are served
 *   cache-first, so a session always runs one consistent version of the game.
 * - Updates: a new version installs in the background and then *waits*. The page
 *   shows "Update ready"; only when the player taps Reload does it take over
 *   (SKIP_WAITING), after which old caches are removed. Nothing ever swaps code
 *   under a game in progress, and saved games (localStorage) are never touched.
 * - Everything else in scope (e.g. the original PNG sheets, only used by
 *   browsers without WebP) is network-first with an offline copy.
 * - Paths are resolved against the registration scope, so the game works from
 *   a GitHub Pages project subpath such as /GRIDLOCK/.
 */

// <precache> generated by tools/build-pwa.mjs; do not edit by hand
const VERSION = 'f92cfe5903df';
const PRECACHE = [
  'assets/fonts/lilita-one-latin-ext.woff2',
  'assets/fonts/lilita-one-latin.woff2',
  'assets/fonts/nunito-latin-ext.woff2',
  'assets/fonts/nunito-latin.woff2',
  'assets/generated/civic-buildings.webp',
  'assets/generated/effects.webp',
  'assets/generated/ownership-markers.webp',
  'assets/generated/parks-open-spaces.webp',
  'assets/generated/props-decor.webp',
  'assets/generated/residential-commercial-buildings.webp',
  'assets/generated/roads-infrastructure.webp',
  'assets/generated/title-menu-decor.webp',
  'assets/generated/ui-buttons-panels.webp',
  'assets/generated/ui-icons.webp',
  'assets/generated/ui/btn-cream.png',
  'assets/generated/ui/btn-disabled.png',
  'assets/generated/ui/btn-gold.png',
  'assets/generated/ui/btn-plain.png',
  'assets/generated/ui/plaque-corners.png',
  'assets/generated/ui/ribbon-blue.png',
  'assets/generated/ui/square-cream.png',
  'assets/generated/ui/toggle-off.png',
  'assets/generated/ui/toggle-on.png',
  'assets/icons/apple-touch-icon.png',
  'assets/icons/icon-192.png',
  'assets/icons/icon-512.png',
  'assets/icons/maskable-512.png',
  'assets/media/cardboard-city.mp3',
  'assets/media/inspire.png',
  'assets/media/inspiresoftwareintro.mp4',
  'assets/media/paper-blocks.mp3',
  'css/art.css',
  'css/base.css',
  'css/components.css',
  'css/desktop.css',
  'css/fonts.css',
  'css/game.css',
  'css/mobile.css',
  'css/screens.css',
  'css/title.css',
  'css/tokens.css',
  'index.html',
  'js/art.js',
  'js/assets.js',
  'js/config.js',
  'js/core/board.js',
  'js/core/bonuses.js',
  'js/core/buildings.js',
  'js/core/bus.js',
  'js/core/career.js',
  'js/core/challenge.js',
  'js/core/cpu/city.js',
  'js/core/cpu/random.js',
  'js/core/cpu/roads.js',
  'js/core/development.js',
  'js/core/economy.js',
  'js/core/events.js',
  'js/core/finance.js',
  'js/core/forecast.js',
  'js/core/game.js',
  'js/core/modes.js',
  'js/core/persistence.js',
  'js/core/rng.js',
  'js/core/scoring.js',
  'js/core/seats.js',
  'js/core/settings.js',
  'js/core/strategy.js',
  'js/core/takeover.js',
  'js/core/tutorial.js',
  'js/main.js',
  'js/pwa.js',
  'js/ui/auctionView.js',
  'js/ui/audio.js',
  'js/ui/boardView.js',
  'js/ui/bonusView.js',
  'js/ui/buildPanel.js',
  'js/ui/careerView.js',
  'js/ui/cityIntro.js',
  'js/ui/cpuDriver.js',
  'js/ui/dom.js',
  'js/ui/eventView.js',
  'js/ui/financeView.js',
  'js/ui/forecastView.js',
  'js/ui/gameView.js',
  'js/ui/haptics.js',
  'js/ui/hud.js',
  'js/ui/intro.js',
  'js/ui/music.js',
  'js/ui/resultsView.js',
  'js/ui/router.js',
  'js/ui/settingsView.js',
  'js/ui/setupView.js',
  'js/ui/startView.js',
  'js/ui/toast.js',
  'js/ui/touchGuard.js',
  'js/ui/tutorial.js',
  'manifest.webmanifest',
];
// </precache>

const PREFIX = 'gridlock-';
const PRECACHE_CACHE = `${PREFIX}precache-${VERSION}`;
const RUNTIME_CACHE = `${PREFIX}runtime-${VERSION}`;
const SCOPE = new URL(self.registration.scope);
const INDEX_URL = new URL('index.html', SCOPE).href;
const PRECACHED = new Set(PRECACHE.map((path) => new URL(path, SCOPE).href));

self.addEventListener('install', (event) => {
  // cache: 'reload' skips the HTTP cache so a new version never stores stale files.
  // addAll is atomic: if any file fails, this version doesn't install and the old one keeps running.
  event.waitUntil(caches.open(PRECACHE_CACHE).then((cache) =>
    cache.addAll([...PRECACHED].map((url) => new Request(url, { cache: 'reload' })))));
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keep = new Set([PRECACHE_CACHE, RUNTIME_CACHE]);
    for (const key of await caches.keys()) {
      if (key.startsWith(PREFIX) && !keep.has(key)) await caches.delete(key);
    }
    // The first install controls the open page at once, so it works offline without a reload.
    await self.clients.claim();
  })());
});

self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
  if (event.data?.type === 'GET_VERSION') event.ports[0]?.postMessage({ version: VERSION });
});

async function fromPrecache(url) {
  return (await caches.open(PRECACHE_CACHE)).match(url);
}

/**
 * fetch() for the page's request that never rejects the FetchEvent: a request the page has
 * cancelled (e.g. an image a style no longer needs) gets an empty reply nobody is waiting for,
 * and a real network failure becomes the same network error the page would see without us.
 */
async function fetchForPage(request) {
  try {
    return await fetch(request);
  } catch {
    if (request.signal?.aborted) return new Response(null, { status: 204, statusText: 'Cancelled' });
    return Response.error();
  }
}

/** Precached copy, or the network if it isn't in the cache (e.g. still installing). */
async function precachedOrNetwork(url, request) {
  return (await fromPrecache(url)) ?? fetchForPage(request);
}

/** Network first, keeping a copy for offline use. */
async function networkFirst(request) {
  const cache = await caches.open(RUNTIME_CACHE);
  const response = await fetchForPage(request);
  if (response.ok && response.status !== 204) {
    await cache.put(request, response.clone()).catch(() => {});
    return response;
  }
  if (response.type === 'error') return (await cache.match(request)) ?? response;
  return response;
}

/** A 206 slice of a cached file for a media range request (416 when the range is outside it). */
async function rangeResponse(request, cached) {
  const body = await cached.arrayBuffer();
  const size = body.byteLength;
  const match = /^bytes=(\d*)-(\d*)$/.exec((request.headers.get('range') ?? '').trim());
  if (!match || (match[1] === '' && match[2] === '')) return new Response(body, { status: 200, headers: cached.headers });
  let start;
  let end;
  if (match[1] === '') { // the last N bytes
    start = Math.max(0, size - Number(match[2]));
    end = size - 1;
  } else {
    start = Number(match[1]);
    end = match[2] === '' ? size - 1 : Math.min(Number(match[2]), size - 1);
  }
  if (start >= size || start > end) {
    return new Response(null, { status: 416, headers: { 'Content-Range': `bytes */${size}` } });
  }
  return new Response(body.slice(start, end + 1), {
    status: 206,
    headers: {
      'Content-Type': cached.headers.get('Content-Type') ?? 'application/octet-stream',
      'Content-Range': `bytes ${start}-${end}/${size}`,
      'Content-Length': String(end - start + 1),
      'Accept-Ranges': 'bytes',
    },
  });
}

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== SCOPE.origin || !url.pathname.startsWith(SCOPE.pathname)) return;

  // The app shell: the scope root or index.html, whatever the query string (?seed=…, ?debug).
  const isShell = request.mode === 'navigate'
    && (url.pathname === SCOPE.pathname || url.href.split(/[?#]/)[0] === INDEX_URL);
  if (isShell) {
    event.respondWith(precachedOrNetwork(INDEX_URL, request));
    return;
  }

  const bare = url.origin + url.pathname;
  if (PRECACHED.has(bare)) {
    // <audio>/<video> ask for byte ranges (Safari insists on a 206 reply): slice the cached file.
    if (request.headers?.has?.('range')) {
      event.respondWith(fromPrecache(bare).then((cached) => (cached ? rangeResponse(request, cached) : fetchForPage(request))));
      return;
    }
    event.respondWith(precachedOrNetwork(bare, request));
    return;
  }
  event.respondWith(networkFirst(request));
});
