/**
 * Keeps the offline/PWA files in step with the game.
 *
 *   node tools/build-pwa.mjs            # refresh sw.js precache list + cache version
 *   node tools/build-pwa.mjs --icons    # also re-render assets/icons/ from the logo sprite
 *   node tools/build-pwa.mjs --check    # exit 1 if sw.js is stale (CI / unit tests)
 *
 * The service worker precaches every file the game needs at runtime. Its cache
 * VERSION is a hash of those files' contents, so any change to HTML/CSS/JS/art
 * produces a new cache, and players get it through the safe update prompt.
 * GitHub Pages runs no build step, so the refreshed sw.js must be committed.
 */
import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';
import { execSync } from 'node:child_process';
import { readFile, readdir, writeFile, mkdir } from 'node:fs/promises';
import { join, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(fileURLToPath(new URL('..', import.meta.url)));
const SW_FILE = join(ROOT, 'sw.js');
const START = '// <precache>';
const END = '// </precache>';

/** Top-level files and folders the game loads at runtime (never the original PNG sheets). */
const PRECACHE_ROOTS = ['index.html', 'manifest.webmanifest', 'css', 'js', 'assets/generated', 'assets/fonts', 'assets/icons', 'assets/media'];
const RUNTIME_EXT = /\.(?:html|webmanifest|css|js|webp|png|woff2|mp3|mp4)$/;
/** PNG fallbacks for browsers without WebP: fetched (and cached) only if a browser asks for them. */
const NOT_PRECACHED = new Set(['assets/generated/props-decor.png']);

/** Icon renders: [file, size, logo width as a share of the canvas]. Maskable keeps the whole sign inside the 40%-radius safe circle. */
export const ICONS = [
  ['icon-192.png', 192, 0.9],
  ['icon-512.png', 512, 0.9],
  ['maskable-512.png', 512, 0.66],
  ['apple-touch-icon.png', 180, 0.84],
];
export const ICON_BACKGROUND = '#2a211a';

async function walk(dir) {
  const out = [];
  for (const entry of await readdir(join(ROOT, dir), { withFileTypes: true })) {
    const path = `${dir}/${entry.name}`;
    if (entry.isDirectory()) out.push(...await walk(path));
    else if (RUNTIME_EXT.test(entry.name)) out.push(path);
  }
  return out;
}

/** Sorted, root-relative paths of every precached file. */
export async function precacheFiles() {
  const files = [];
  for (const entry of PRECACHE_ROOTS) {
    files.push(...(RUNTIME_EXT.test(entry) ? [entry] : await walk(entry)));
  }
  return files.map((f) => f.split(sep).join('/')).filter((f) => !NOT_PRECACHED.has(f)).sort();
}

/** Content hash of the precache: changes whenever any cached byte (or the file list) changes. */
export async function precacheVersion(files) {
  const hash = createHash('sha256');
  for (const file of files) {
    hash.update(`${file}\0`);
    hash.update(await readFile(join(ROOT, file)));
  }
  return hash.digest('hex').slice(0, 12);
}

export async function renderPrecacheBlock() {
  const files = await precacheFiles();
  const version = await precacheVersion(files);
  const list = files.map((f) => `  '${f}',`).join('\n');
  return `${START} generated by tools/build-pwa.mjs; do not edit by hand\nconst VERSION = '${version}';\nconst PRECACHE = [\n${list}\n];\n${END}`;
}

/** sw.js with its generated block refreshed. */
export async function updatedServiceWorker() {
  const sw = await readFile(SW_FILE, 'utf8');
  const start = sw.indexOf(START);
  const end = sw.indexOf(END);
  if (start < 0 || end < start) throw new Error('sw.js is missing its // <precache> … // </precache> block');
  return { current: sw, next: sw.slice(0, start) + await renderPrecacheBlock() + sw.slice(end + END.length) };
}

async function loadPlaywright() {
  try { return await import('playwright'); } catch {
    const g = execSync('npm root -g').toString().trim();
    return createRequire(`${g}/`)('playwright');
  }
}

/** Renders the title logo sprite onto the tabletop colour (uses Playwright's Chromium canvas; no image libraries). */
async function buildIcons() {
  const { SHEETS } = await import('../js/assets.js');
  const title = SHEETS.title;
  const [sx, sy, sw, sh] = title.sprites.logo;
  const src = `data:image/png;base64,${(await readFile(join(ROOT, title.file))).toString('base64')}`;
  const { chromium } = await loadPlaywright();
  const browser = await chromium.launch(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {});
  const page = await browser.newPage();
  await page.setContent('<canvas id="c"></canvas>');
  await mkdir(join(ROOT, 'assets/icons'), { recursive: true });
  for (const [file, size, share] of ICONS) {
    const png = await page.evaluate(async ({ src, sx, sy, sw, sh, size, share, bg }) => {
      const img = new Image();
      img.src = src;
      await img.decode();
      const c = document.getElementById('c');
      c.width = size;
      c.height = size;
      const x = c.getContext('2d');
      x.fillStyle = bg;
      x.fillRect(0, 0, size, size);
      // Warm lamplight behind the sign, like the title screen's tabletop.
      const glow = x.createRadialGradient(size / 2, size / 2, 0, size / 2, size / 2, size * 0.62);
      glow.addColorStop(0, 'rgba(255, 214, 140, 0.34)');
      glow.addColorStop(1, 'rgba(255, 214, 140, 0)');
      x.fillStyle = glow;
      x.fillRect(0, 0, size, size);
      const w = size * share;
      const h = (w * sh) / sw;
      x.imageSmoothingQuality = 'high';
      x.drawImage(img, sx, sy, sw, sh, (size - w) / 2, (size - h) / 2, w, h);
      return c.toDataURL('image/png');
    }, { src, sx, sy, sw, sh, size, share, bg: ICON_BACKGROUND });
    await writeFile(join(ROOT, 'assets/icons', file), Buffer.from(png.split(',')[1], 'base64'));
    console.log(`✔ assets/icons/${file} (${size}×${size})`);
  }
  await browser.close();
}

async function main() {
  const check = process.argv.includes('--check');
  if (process.argv.includes('--icons') && !check) await buildIcons();
  const { current, next } = await updatedServiceWorker();
  if (check) {
    if (current !== next) {
      console.error('✘ sw.js precache is stale: run `npm run build:pwa` and commit sw.js');
      process.exit(1);
    }
    console.log('✔ sw.js precache is up to date');
    return;
  }
  if (current !== next) await writeFile(SW_FILE, next);
  const files = await precacheFiles();
  console.log(`✔ sw.js: ${files.length} files, version ${await precacheVersion(files)}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) await main();
